# Generated by Django 4.2.5 on 2024-08-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='category',
            field=models.CharField(default='Default Category', max_length=50),
        ),
        migrations.AddField(
            model_name='app',
            name='link',
            field=models.URLField(default='http://example.com'),
        ),
        migrations.AddField(
            model_name='app',
            name='sub_category',
            field=models.CharField(default='Default Category', max_length=100),
        ),
        migrations.DeleteModel(
            name='UserTask',
        ),
    ]
