# Generated by Django 4.2.5 on 2024-08-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_app_category_app_link_app_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='image',
            field=models.ImageField(default='app_images/default.png', upload_to='app_images/'),
        ),
    ]
